#!/bin/bash

docker run --name mediatomb --network host -p 41570:41570 -p 1900:1900/udp -p 49152:49152 -p 50500:50500 -p 50500:50500/udp -v /mnt/nfs/SATA8TB/Video:/media -d mitshel/mediatomb
#docker run --name mediatomb --network host -d mitshel/mediatomb
#50500/tcp 49152/tcp 1900/udp
sleep 5
./mtomb add /media
