registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
#  environment:
#    REGISTRY_HTTP_TLS_LETSENCRYPT_CACHEFILE: /cache.letsencrypt
#    REGISTRY_HTTP_TLS_LETSENCRYPT_EMAIL: hello@vtg.gazprom.ru
#    REGISTRY_AUTH: htpasswd
#    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
#    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm  
  volumes:
    - /home/docker/docker-registry/registry:/var/lib/registry 
#    - /home/docker/docker-registry/auth:/auth
#    - /etc/letsencrypt/live/vtg.gazprom.ru:/certs
